# Python Numpy Tutorial

In this notebook, I will be completing the Python Numpy Tutorial found on CS231 (Deep Learning at Stanford).

### Datatypes
Understanding different *Datatypes* for Python:

| Datatype | Keyword | Description | Example |
| :--- | :--- | :--- | :--- |
| integer | `int` | positive/negative whole numbers | `42` |
| floating point number | `float` | real number in decimal form | `3.1416` |
| complex number | `complex` | complex number $a+b\sqrt{-1}$ | `1+2j` |
| boolean | `bool` | true or false | `True` |
| string | `str` | text | `"Hello World"` |

In [47]:
x = 3.2  # Change x to different values and see the different types!
print(type(x))

y = int(x)  # We can also convert to a different datatype.
print(type(y))

<class 'float'>
<class 'int'>


Numbers use the usual operations: `+`, `-`, `*`, `/`, `//`, `**`

In [56]:
print(y + x)
print(y * x)
print(y / x)
print(y // x)
print(y ** x)

6.2
9.600000000000001
0.9375
0.0
33.63473536961897


Booleans are logical factors. They just come in two values "True" or "False". In Python, we use words rather than symbols to make the logical operations `or`, `and`, `not`, `!=`.

In [66]:
t, f = True, False
print(t or f)
print(t and f)
print(not f)
print(f != f) #Boolean operators include <, >, <=, >=, == as well.

True
False
True
False


Everything in Python is an object. And it has different methods. Strings in python are objects which methods are capitlize, lower case, upper case, among others. We can also use format to enter information as an input.

In [58]:
all_caps = "HELLO!"
all_caps.lower() # Go to strings documentation and try different methods.

'hello!'

In [62]:
template = "Hello, my name is {0}. I live in {1}."

In [63]:
template.format('Socorro', 'Vancouver')

'Hello, my name is Socorro. I live in Vancouver.'

In [64]:
template.format('Sigmund', 'Germany')

'Hello, my name is Sigmund. I live in Germany.'

### Containers
Containers are also important and should be studied carefully:

| Container | Keyword | Description | Example |
| :--- | :--- | :--- | :--- |
| list | `list` | homogeneous sequence representing a collection of similar objects | `['Ali','Juan','Jean']` |
| tuple | `tuple` | heterogeneous sequence representing a single object | `('Thursday',6,9,2018)` |
| dictionary | `dict` | mapping of key-value pairs | `{'name':'CS','code':101,'credits':10}` |

Lists and tuples are also considered sequence types.

In [73]:
my_list = [1,2,3,4,5]
my_tuple = (1,2,3,4,5)

print(type(my_list))
print(type(my_tuple))

<class 'list'>
<class 'tuple'>


In [74]:
# Methods for lists
my_list.append(6)
my_list

[1, 2, 3, 4, 5, 6]

In [75]:
my_list.count(2) # Frequency of the item between parenthesis.

1

In Python, indices go from 0 to the length of the list minus 1

In [83]:
# Slicing
print(my_list[2:4])    # Slice from index 2 to 4 (exclusive)
print(my_list[2:])     # Slice from index 2 to the end
print(my_list[:2])     # Slice from the start to index 2 (exclusive)
print(my_list[:])      # Slice of the whole list
print(my_list[:-1])    # Slice from the beginning to the last item of the list (exclusive)

[3, 4]
[3, 4, 5, 6]
[1, 2]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5]


In [89]:
len(my_list)  # It is 6
my_list[6]  # Needs to be 5 at most

IndexError: list index out of range

In [81]:
# List comprehension
squares = [x ** 2 for x in my_list]
print(squares) 

[1, 4, 9, 16, 25, 36]


In [91]:
# I can change an item in lists by accessing it through its index
my_list[5] = 10
my_list

[1, 2, 3, 4, 5, 10]

Inmutable data types (tuples)

In [93]:
# Can't change a tuple through slicing
print(my_tuple[2])
my_tuple[2] = 5

3


TypeError: 'tuple' object does not support item assignment

### Loops

Iterates all items in a list/array.

In [95]:
word = "Python"
for letter in word:
    print("Gimme a " + letter + "!")

print("What's that spell?!! " + word + "!")

Gimme a P!
Gimme a y!
Gimme a t!
Gimme a h!
Gimme a o!
Gimme a n!
What's that spell?!! Python!


### Dictionaries

A dictionary is a mapping between key-values pairs.

In [144]:
house = {'bedrooms': 3, 'bathrooms': 2, 'city': 'Vancouver', 'price': 1000000, 'date_sold': (1,3,2015),'type':'house'}
appartment = {'bedrooms': 2, 'bathrooms': 1, 'city': 'Burnaby', 'price': 699999, 'date_sold': (27,8,2011), 'type':'appartment'}

In [145]:
house['price']

1000000

In [146]:
appartment['date_sold']

(27, 8, 2011)

In [147]:
for x in [house, appartment]:
    print('This is a: ', x['type'])
    for housing_detail in x:
        keys = x[housing_detail]
        print('{0}: {1}'.format(housing_detail, keys))

This is a:  house
bedrooms: 3
bathrooms: 2
city: Vancouver
price: 1000000
date_sold: (1, 3, 2015)
type: house
This is a:  appartment
bedrooms: 2
bathrooms: 1
city: Burnaby
price: 699999
date_sold: (27, 8, 2011)
type: appartment


### Functions

Define a function called `square` which takes one input parameter `n` and returns the square `n**2`.

In [148]:
def square(n):
    square = n**2
    return square

In [149]:
square(5)

25

## Numpy
Core scientific computation for Python


In [1]:
# Load libraries
import numpy as np

An np.array is a grid of values of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [168]:
a = np.array([[1,2,3],[3,5,6]])  # Create a rank 2 array
print(type(a), a.shape) 
print(a[0], a[1:2])

<class 'numpy.ndarray'> (2, 3)
[1 2 3] [[3 5 6]]


In [174]:
# Ways to create arrays
# Other ways include random (random) or constant (full), identity (eye)
b = np.zeros((3,3))  # Create an array of all zeros
c = np.ones((3,3))   # Create an array of all ones
print(b)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Arrays can be indexed same as Python lists.

In [177]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Slicing to pull out the subarray of the first 2 rows and columns 1 and 2

b = a[:2, 1:3]
print(b)

[[2 3]
 [5 6]]


In [184]:
# Accessing rows and columns
row_r1 = a[0, :]    # First row of a  
col_r1 = a[:, 0]    # First column of a  
print(a)
print('row 1: ', row_r1)
print('column 1: ', col_r1)

[[1 2 3]
 [3 5 6]]
row 1:  [1 2 3]
column 1:  [1 3]


Arrays can have multiple operations:

In [198]:
x = np.array([[1,2],[0,1]])
y = np.array([[8,9],[7,8]])

# Addition
print('sum:\n', x + y)

# Substraction
print('substraction:\n', x - y)

# Multiplication
print('multiplication:\n', x * y)

# Elementwise division
print('division:\n', x / y)

# Dot product
print('dot product: \n', x.dot(y))

# Transpose
print('transpose: \n', x.T)

sum:
 [[ 9 11]
 [ 7  9]]
substraction:
 [[-7 -7]
 [-7 -7]]
multiplication:
 [[ 8 18]
 [ 0  8]]
division:
 [[0.125      0.22222222]
 [0.         0.125     ]]
dot product: 
 [[22 25]
 [ 7  8]]
transpose: 
 [[1 0]
 [2 1]]


In [199]:
# Computation on arrays
print(np.sum(x))  # Compute sum of all elements"
print(np.sum(x, axis=0))  # Compute sum of each column"
print(np.sum(x, axis=1))  # Compute sum of each row"

4
[1 3]
[3 1]


### Broadcasting

Many times, we want to add a smaller vector into a larger vector. What we would expect to happen, is that the smaller vector would be reused as long as the larger vector needs it. 

For this purpose, we have broadcasting.

In [200]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This was just a small review of datatypes and numpy basics.

The next Jupyter notebook will be using matplotlib.